//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Answer
    {
        public Answer()
        {
            this.ChildQuestion = new HashSet<Question>();
            this.SelectorSet = new HashSet<SelectorSet>();
        }
    
        public int Id { get; set; }
        
        public string Val { get; set; }
        public Nullable<int> QuestionId { get; set; }
    
        public virtual Question ParentQuestion { get; set; }
        public virtual ICollection<Question> ChildQuestion { get; set; }
        public virtual ICollection<SelectorSet> SelectorSet { get; set; }
    }
}
