//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class ExpertSystem
    {
        public ExpertSystem()
        {
            this.Property = new HashSet<Property>();
            this.Item = new HashSet<Item>();
            this.Survey = new HashSet<Survey>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsPublished{ get; set; }
    
        public virtual ICollection<Property> Property { get; set; }
        public virtual ICollection<Item> Item { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Survey> Survey { get; set; }
    }
}
