//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Log
    {
        
        public Log()
        {
            this.NextLog = new HashSet<Log>();
            this.TempRemovedItem = new HashSet<TempLogItem>();
        }
    
        public int Id { get; set; }
        public int QId { get; set; }
        public int AnswId { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public int PropId { get; set; }
        public Nullable<int> LogId { get; set; }
    
        public virtual Survey Survey { get; set; }
        public virtual ICollection<Log> NextLog { get; set; }
        public virtual Log PrevLog { get; set; }
        public virtual ICollection<TempLogItem> TempRemovedItem { get; set; }
    }
}
