//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Item> ItemSet { get; set; }
        public DbSet<Property> PropertySet { get; set; }
        public DbSet<Val> ValSet { get; set; }
        public DbSet<Question> QuestionSet { get; set; }
        public DbSet<Answer> AnswerSet { get; set; }
        public DbSet<Note> NoteSet { get; set; }
        public DbSet<SelectorSet> SelectorSet { get; set; }
        public DbSet<ExpertSystem> ExpertSystemSet { get; set; }
        public DbSet<User> UserSet { get; set; }
        public DbSet<Log> LogSet { get; set; }
        public DbSet<Survey> SurveySet { get; set; }
        public DbSet<SurveyItem> SurveyItemSet { get; set; }
        public DbSet<TempLogItem> TempLogItemSet { get; set; }
    }
}
